### ISSUE TITLE
Odd generation of optional fields

### ISSUE THREAD

**Issue by okkero** [andreasewering/protoc-gen-elm#197] opened 2023-04-03 11:40 UTC
I think it is a bit strange the way optional fields are generated. For example, with the following message definition:
```protobuf
message Foo {
  optional uint32 n = 1;
}
```
instead of simply generating a record type with `n : Maybe Int`, a new type `type Foo_N = Foo_N Int` is created (or, in 3.0.0 beta: `type N = N Int`), and the field in the message is `n : Maybe Foo_N`.

There might be a good reason for doing it like this, but right now I can't see it. From where I stand it seems like an unnecessary piece of complexity that makes the data more difficult to work with. Perhaps you could shed some light on this? Thank you.

**Comment by andreasewering** [comment] 2023-04-04 07:11
That is most likely a bug. I'll add a regression test and figure out why the unnecessary wrapper occurs. Wrappers should only be necessary in recursive messages.

**Comment by andreasewering** [comment] 2023-04-04 19:22
I just published protoc-gen-elm@3.0.0-beta.1 which should fix this weird behaviour.

**Comment by andreasewering** [comment] 2023-04-06 20:12
I'll close this for now, since I released 3.0.0. Feel free to reopen if you encounter the issue again.

**Closed by andreasewering** 2023-04-06 20:12 UTC

**Comment by okkero** [comment] 2023-04-07 08:18
Hi. Thank you for looking into that. I finally have some time to give this a try today.

**Comment by okkero** [comment] 2023-04-07 09:21
I think this broke generation for optional enum fields. Looks like a simple fix, but I don't know how easy it is to actually implement.

Consider the following protobuf code:

```protobuf
enum Enum {
  A = 0;
  B = 1;
}

message Foo {
  optional Enum e = 1;

  // Working optional field, for reference
  optional int32 i = 2;
}
```

It will generate the following decoder and encoder:
```elm
decodeProto__Foo__V1__Foo : Protobuf.Decode.Decoder Proto__Foo__V1__Foo
decodeProto__Foo__V1__Foo =
    Protobuf.Decode.message
        defaultProto__Foo__V1__Foo
        [ Protobuf.Decode.optional 1 decodeProto__Foo__V1__Enum (\a r -> { r | e = a })
        , Protobuf.Decode.optional 2 (Protobuf.Decode.map Just Protobuf.Decode.int32) (\a r -> { r | i = a })
        ]


encodeProto__Foo__V1__Foo : Proto__Foo__V1__Foo -> Protobuf.Encode.Encoder
encodeProto__Foo__V1__Foo value =
    Protobuf.Encode.message
        [ ( 1, encodeProto__Foo__V1__Enum value.e )
        , ( 2, (Maybe.map Protobuf.Encode.int32 >> Maybe.withDefault Protobuf.Encode.none) value.i )
        ]
```

This fails to compile, as Proto__Foo__V1__Foo expects a `Maybe Proto__Foo__V1__Enum`, but the decoder and encoder assume it is not a `Maybe`. It should probably generate code for the enum field similar to the code generated for the int field, like the following:

```elm
decodeProto__Foo__V1__Foo : Protobuf.Decode.Decoder Proto__Foo__V1__Foo
decodeProto__Foo__V1__Foo =
    Protobuf.Decode.message
        defaultProto__Foo__V1__Foo
        [ Protobuf.Decode.optional 1 (Protobuf.Decode.map Just decodeProto__Foo__V1__Enum) (\a r -> { r | e = a })
        , Protobuf.Decode.optional 2 (Protobuf.Decode.map Just Protobuf.Decode.int32) (\a r -> { r | i = a })
        ]


encodeProto__Foo__V1__Foo : Proto__Foo__V1__Foo -> Protobuf.Encode.Encoder
encodeProto__Foo__V1__Foo value =
    Protobuf.Encode.message
        [ ( 1, (Maybe.map encodeProto__Foo__V1__Enum >> Maybe.withDefault Protobuf.Encode.none) value.e )
        , ( 2, (Maybe.map Protobuf.Encode.int32 >> Maybe.withDefault Protobuf.Encode.none) value.i )
        ]
```
I tested this by manually editing the generated file, and it seems to work.

**Comment by andreasewering** [comment] 2023-04-07 16:16
Thanks for finding this problem! I did not handle the Proto3Optional case correctly for the enum de/encoders.
Should work with version 3.0.1 now.

**Comment by okkero** [comment] 2023-04-07 17:42
Yeah, works great. Thank you!
